### ISSUE TITLE
Cancelling block place events passes physics update

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#204]
Placed redstone wire interacts with redstone torches, even when block place is cancelled.

**Comment by tomasalves8** [comment]
Could not reproduce, what steps did you take to find this?

**Comment by andreasdc** [comment]
> Could not reproduce, what steps did you take to find this?

Placed redstone wire has to be 1-2 blocks from redstone torch.

**Comment by andreasdc** [comment]
I think applying physics was done even with BlockPlaceEvent cancelled.

**Comment by tomasalves8** [comment]
https://cdn.discordapp.com/attachments/910177343153258546/910198135106715668/2021-11-16_16-01-18.mkv

**Comment by andreasdc** [comment]
> https://cdn.discordapp.com/attachments/910177343153258546/910198135106715668/2021-11-16_16-01-18.mkv

You check redstone or physics update?

**Comment by tomasalves8** [comment]
Take a screenshot or a video.

**Comment by andreasdc** [comment]
> Take a screenshot or a video.

Can you try? I will have environment in some time and I don't know if I will be available.

**Comment by tomasalves8** [comment]
No problem I can wait.

**Comment by andreasdc** [comment]
> No problem I can wait.

Sure but can you try?

**Comment by tomasalves8** [comment]
No, I will wait for you to show **exactly** how to reproduce this issue.

**Comment by andreasdc** [comment]
> No, I will wait for you to show **exactly** how to reproduce this issue.

Don't get **offended**

**Comment by andreasdc** [comment]
??? @Lucaskyy can you check this behaviour?

**Comment by Rastrian** [comment]
> > Then don't **waste** my time :)
> 
> ??? @Lucaskyy can you check this behaviour?

pay our hour rate and you can waste our time all day dude.

**Comment by andreasdc** [comment]
> > > Then don't **waste** my time :)
> > 
> > 
> > ??? @Lucaskyy can you check this behaviour?
> 
> pay our hour rate and you can waste our time all day dude.

You pay my and we can talk. :P If you don't want to fix don't comment and don't take actions in issues, wtf?

**Comment by andreasdc** [comment]
> No problem I can wait.

In 14 minutes he changed attitude let me know if you still want my help or you fix this without me wasting your time.

**Comment by Lucaskyy** [comment]
Sigh..

**Comment by tomasalves8** [comment]
You are acting like we owe you something, you either want to contribute and share your issue or you don't. I said that I would wait for a screenshot of your problem.

**Comment by andreasdc** [comment]
> You are acting like we owe you something, you either want to contribute and share your issue or you don't. I said that I would wait for a screenshot of your problem.

I'm reporting the bug and you tell me to not waste your time by sending a video of this bug reproduction? Make a decision if you want my help or not.

**Comment by andreasdc** [comment]
> That's not what he was saying.. He tells you that he will wait, you continue to say that he should try again while it didn't work for him. So, he doesn't want to waste his time endlessly trying to reproduce something.

Ah right, but he for sure stepped too far with wasting time, it could ended when he said that he can't try, little misunderstanding.

**Comment by Lucaskyy** [comment]
I understand, no problem. I think he might got a little frustrated since the same thing happened a couple hours ago with a different issue, which I can understand if that's the case. Either way, don't make too big of a hazzle about it. It's fine now.

**Comment by Lucaskyy** [comment]
Also, @andreasdc when you test this and send us a reproduction video please make sure you're on the latest version of NachoSpigot. **Not** your fork.

**Comment by andreasdc** [comment]
> Also, @andreasdc when you test this and send us a reproduction video please make sure you're on the latest version of NachoSpigot. **Not** your fork.

It's easy to reproduce, but I have met another problems and my lack of availabilty just appeared, I have to go out and I will be back in couple hours, that's why I said that. I will do that today if you won't check that earlier by me. 🐰

**Comment by Lucaskyy** [comment]
@andreasdc Any success?

**Comment by andreasdc** [comment]
> @andreasdc Any success?

Yes. When you place a redstone dust 1 block further from redstone torch, it will update redstone torch and if this torch can't be placed normally on that block (only with worldedit), it will destroy this torch.
Cancelling BlockPlaceEvent doesn't help, cancelling PlayerInteractEvent removes this bug.

**Comment by andreasdc** [comment]
@Lucaskyy umm, this doesn't fix it. Read commit's discussion.

**Comment by Elierrr** [comment]
> Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled

**Comment by andreasdc** [comment]
> > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled

Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.

Test and say something, ok?

**Comment by LewUwU** [comment]
> > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> 
> Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> 
> Test and say something, ok?

I don't know what's wrong here.

I fixed your issue 'Cancelling block place events passes physics update'

Your issue is when cancelling the place event, the world do a physics update, i don't care about the 'bug' of 'PandaWire', Nacho doesn't support forks (you're using your own fork)

**Comment by andreasdc** [comment]
> > > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > 
> > 
> > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> > Test and say something, ok?
> 
> I don't know what's wrong here.
> 
> I fixed your issue 'Cancelling block place events passes physics update'
> 
> Your issue is when cancelling the place event, the world do a physics update, i don't care about the 'bug' of 'PandaWire', Nacho doesn't support forks (you're using your own fork)

"Placed redstone wire interacts with redstone torches, even when block place is cancelled."
Did you fix it? Check debug og applyPhysics when placing redsone then comeback.

**Comment by Lucaskyy** [comment]
Okay, so, if anything, you can still reproduce this issue on the latest build of NachoSpigot? That's all I care about.

**Comment by andreasdc** [comment]
> Okay, so, if anything, you can still reproduce this issue on the latest build of NachoSpigot? That's all I care about.

To the latest Nacho I can't add my own debug, if you want you can add it and test, I can test it soon by myself.

**Comment by Lucaskyy** [comment]
Well, I'm busy working on other things, I don't have time for that now.
> To the latest Nacho I can't add my own debug,

Yes, you can? Just clone the repo, add the debug stuff you want to add, compile and test?

**Comment by andreasdc** [comment]
> ?

I'm busy working on other things too, I will do that today.

**Comment by LewUwU** [comment]
> Placed redstone wire interacts with redstone torches, even when block place is cancelled.

Interact / Place

You're using the wrong event lmao
You need to use BlockRedstoneEvent

**Comment by andreasdc** [comment]
> BlockRedstoneEvent

What event is scalled when you place redstone dust?

**Comment by LewUwU** [comment]
> > BlockRedstoneEvent
> 
> What event is called when you place redstone dust?

That's another world, place and interact is not the same

**Comment by Lucaskyy** [comment]
Also, keep in mind, Lew fixed the bug that this issue was made for. You're then telling that Lew did not fix **a completely DIFFERENT issue**, so if you find something else, make another issue for it and prove that it's reproduce-able on NachoSpigot. Like I said multiple times already, we do not know your codebase, you might've screwed something up yourself but we cannot ever know since your code is private.

**Comment by andreasdc** [comment]
> Also, keep in mind, Lew fixed the bug that this issue was made for. You're then telling that Lew did not fix **a completely DIFFERENT issue**, so if you find something else, make another issue for it and prove that it's reproduce-able on NachoSpigot. Like I said multiple times already, we do not know your codebase, you might've screwed something up yourself but we cannot ever know since your code is private.

Placed redstone wire interacts with redstone torches

The issue is still the same. I will test with the newest Nacho, don't worry.

**Comment by andreasdc** [comment]
I'm sure this bug is still in Nacho.

**Comment by andreasdc** [comment]
Also my friend BlockRedstoneEvent is not called when placing redstone dust as I see.

**Comment by Lucaskyy** [comment]
Here, look.

When you place redstone, a BlockPlace event is called. Cancelling this will cancel the block place.
But, the redstone will still update. To block this, you need to cancel the BlockRedstoneEvent.

**Comment by andreasdc** [comment]
> .

Pretty weird situation isnt it?

**Comment by Lucaskyy** [comment]
Although, looking at Lew's screen right now, this is not the case!
When blocking the place event, the redstone is never updated.
So what I just said, never happens.

**Comment by andreasdc** [comment]
> .

I debugged applyPhysics and it was reached, I will test it today for sure.

**Comment by Lucaskyy** [comment]
Nvm, I misunderstood. So yes, you should cancel both the BlockPlaceEvent AND the BlockRedstoneEvent.
So it seems that I was right.

The placement itself is cancelled, but the redstone signal update is not. That is just how they did it, this is not a Nacho issue.
**End of discussion.**
The titled issue has been fixed, and the other "issue" you're talking about is normal since that's how it was done.

**Comment by Lucaskyy** [comment]
Also, the redstone signal is a **state**. Not a **block**. So in fact, you cancel everything about the **block** placement, but nothing about the redstone signal **state**. That's done somewhere completely else!
